pull_request_rules:
    - name: Merge all pull requests
      conditions:
        - or:
            - files=package.json
            - files=package-lock.json
      actions:
         merge:
           method: squash
    - name: Delete Branch After Merge
      conditions:
        - squashed
      actions:
         delete_head_branch: {}
