pull_request_rules:
    - name: Merge all pull requests
      actions:
         merge:
           method: merge
    - name: Delete Branch After Merge
      conditions:
        - merged
      actions:
         delete_head_branch: {}
